config/routes.rb
Lasica::Application.routes.draw do
  resources :orders

  resources :line_items

  resources :carts

  get "users/new"

  get "menu/home"
  get "menu/my_cart"
  get "menu/news"

  resources :products
  resources :sessions
  resources :users

  match '/your_cart' => "carts#your_cart", :as => "your_cart"
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/my_account' => "users#show", :as => "my_account"









  root :to => "menu", :action => "home"


end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :line_items, :dependent => :destroy

  def add_product(product)
    current_item = line_items.where(:product_id =>
                                        product.id).first
    if current_item
      current_item.quantity += 1
    else
      current_item = LineItem.new(:product_id =>
                                      product.id)
      line_items << current_item
    end
    current_item
  end

  def total_price
   line_items.to_a.sum {|item| item.total_price}
  end
  #def total_price
  # total = 0
  #  line_items.each do |line_item|
  #    total += line_item.product.price * line_item.quantity
  #  end
    #total
 # end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    if is_admin?
      @carts = Cart.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @carts }
      end
    else
      redirect_to products_path
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  def your_cart
    redirect_to :action => "show", :id => current_cart.id
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

<p><%= render :partial => 'items', :locals => {:cart => current_cart} %></p>

<div>
  <%= render :partial => 'checkout_buttons' %>
  <%= button_to 'Empty cart', @cart, :method => :delete, :confirm => 'Are you sure?' %>
</div>

<div>
  <%= link_to 'Continue shopping', products_path %>
</div>

app/views/carts/_checkout_buttons.html.erb
<% if logged_in? %>
    <%= button_to 'Checkout', new_order_path, method: :get %>
<% else %>
    <%= button_to 'Login to checkout', login_path %>
<% end %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/_items.html.erb
<table>
  <% cart.line_items.each do |item| %>
      <tr>
        <td> <%= item.quantity %> &times;</td>
        <td> <%= item.product.name %></td>
        <td class="item_price"><%= number_to_currency(item.total_price, :unit => '&euro;') %></td>
        <td><%= button_to 'Remove', item, :method => :delete, :confirm => 'Are you sure?' %></td>
      </tr>
  <% end %>
  <tr class="total_line " >
    <td colspan="2">Total</td>
    <td class="total_cell"><%= number_to_currency(cart.total_price, :unit => '&euro;') %></td>
  </tr>
</table>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

<div class="cart_title">Your Cart
    <%= render @cart %>
</div>