config/routes.rb
Lasica::Application.routes.draw do
  resources :orders

  resources :line_items

  resources :carts

  get "users/new"

  get "menu/home"
  get "menu/my_cart"
  get "menu/news"

  resources :products
  resources :sessions
  resources :users

  match '/your_cart' => "carts#your_cart", :as => "your_cart"
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/my_account' => "users#show", :as => "my_account"









  root :to => "menu", :action => "home"


end

app/views/layouts/_header.html.erb
<div id='header'>
  <% if logged_in? %>
      <p>Welcome <%= current_user.first_name %> <%= current_user.last_name %></p>
      <%= button_to 'My_account', my_account_url %>
      <% if is_admin? %>
          <%= button_to 'Users', users_url, method: :get %>
          <%= button_to 'Carts', carts_url, method: :get %>
          <%= button_to 'Orders', orders_url, method: :get %>
      <% end %>
      <%= button_to 'Logout', logout_path %>
  <% else %>
      Hello, <%= button_to 'Create an account', new_user_url, method: :get%>
      <%= form_tag sessions_path do %>
          <div class="field">
            <%= label_tag :email %><br />
            <%= text_field_tag :email %>
          </div>
          <div class="field">
            <%= label_tag :password %><br />
            <%= password_field_tag :password %>
          </div>
          <div class="actions">
            <%= submit_tag 'Login' %>
          </div>
      <% end %>
  <% end %>
</div>

app/views/layouts/_left_nav.html.erb
<div id="side">

  <div id="cart">
    <% if current_cart.line_items.empty? %>
        <p>Your Cart is empty</p>
    <% else %>
        <div class="cart_title">Your Cart</div>
        <%= render :partial => 'carts/items', :locals => {:cart => current_cart} %>
        <%= render :partial => 'carts/checkout_buttons' %>
    <% end %>
    <%= button_to "Edit Your Cart", :controller => "carts", :action => "your_cart" %>
  </div>

  <ul>
    <li><%= link_to "Available Games", products_path %></li>
    <li><%= link_to 'Sell your game', :controller => "products", :action => "new" %></li>
    <li><%= link_to "Home", :controller => "menu", :action => "home" %></li>
    <% if logged_in? %>
        <li> <%= link_to "My_Account", :controller => "users", :action => "show" %></li>
    <% else %>
        <li><%= link_to "Create an account", new_user_url %></li>
    <% end %>
    <li> <%= link_to "News", :controller => "menu", :action => "news" %></li>
  </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Board World</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
<div id="banner">
  <%= @page_title || "Board World" %>
</div>

<div id="columns">

  <%= render :partial => 'layouts/left_nav' %>

  <%= render :partial => 'layouts/header' %>


  <div id="main">
    <%= yield %>
  </div>


</div>

</body>
</html>